<?php /* @var \T4webAuthorization\Controller\ViewModel\User\IndexViewModel $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <?= $this->translate('Please Sign In'); ?>
                </h3>
            </div>

            <div class="panel-body">
                <form action="<?=$this->url('login'); ?>" method="post">
                    <fieldset>
                        <div class="form-group <?= ($viewModel->getForm()->getMessages('uname')) ? 'has-error' : ''; ?>">
                            <?= $this->formText($viewModel->getForm('uname')); ?>
                            <?= $this->formElementErrors($viewModel->getForm('uname'), array('class' => 'help-block')); ?>
                        </div>

                        <div class="form-group <?= ($viewModel->getForm()->getMessages('password')) ? 'has-error' : ''; ?>">
                            <?= $this->formPassword($viewModel->getForm('password')); ?>
                            <?= $this->formElementErrors($viewModel->getForm('password'), array('class' => 'help-block')); ?>
                        </div>

                        <div class="checkbox">
                            <label>
                                <?= $this->formCheckbox($viewModel->getForm('rememberMe')); ?>
                                <?= $this->translate('Remember Me'); ?>

                                <?= $this->formElementErrors($viewModel->getForm('rememberMe'), ['class' => 'help-block']); ?>
                            </label>
                        </div>

                        <button type="submit" class="btn btn-lg btn-success btn-block">
                            <?= $this->translate('Login'); ?>
                        </button>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
